repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        args: [--in-place, --parallel, --recursive]
        additional_dependencies: [toml]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
    -   id: pyupgrade
        # --py310-plus doesn't work with self-referencing literal type hints
        # (tries to convert `Optional['BaseModel']` to `'BaseModel' | None`, which is invalid)
        args: [--py39-plus]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: .env/bin/pylint
        language: system
        types: [python]
        require_serial: false
        args: [--rcfile=pylint.rc, --jobs=0]
